### ISSUE TITLE
Dark logos are hard to see in dark mode

### ISSUE THREAD

**Issue by gnarlex** [adrianvillanueva997/adrianvillanueva997#1]
Love your personal README 💕 Very creative 👏

Black/dark logos are almost invisible to dark mode users:

![Screenshot 2021-03-08 at 16 21 42](https://user-images.githubusercontent.com/24435169/110341895-21908300-802b-11eb-8121-d5fb1b3a391f.png)

I understand they are dynamically loaded in but I'd consider creating "local" versions with white outlines.

Creating an issue on someone else's personal README is the most random thing I've done in a long time. But since I love it so much I just wanted to let you know 🙏

**Comment by adrianvillanueva997** [comment]
Thank you for your kind words about my README! :) 

I know they aren't visible at all for dark mode users, I should fix that anytime soon, probably i should try to find light logos or something, I am not a frontend guy at all haha
